// Comprehensive API Test Suite & Response Generator
const fs = require('fs');
const path = require('path');

const BASE_URL = 'http://localhost:8080/api/v1';
const OUTPUT_FILE = path.join(__dirname, '..', 'API_TEST_RESULTS.md');

const reportSections = [];

function appendHeader() {
  reportSections.push('# Comprehensive API Execution & Verification Report\n');
  reportSections.push('This document provides verified HTTP requests and live responses generated by executing every API endpoint against the running application.\n');
  reportSections.push(`- **Execution Timestamp**: ${new Date().toISOString()}`);
  reportSections.push(`- **Base URL**: \`${BASE_URL}\``);
  reportSections.push(`- **Environment**: Spring Boot 3 + Embedded PostgreSQL Compatibility Mode\n`);
  reportSections.push('---\n');
}

async function testEndpoint({ name, method, endpoint, headers = {}, body = null, notes = '' }) {
  const url = `${BASE_URL}${endpoint}`;
  const reqHeaders = {
    'Accept': 'application/json',
    ...headers
  };
  if (body) {
    reqHeaders['Content-Type'] = 'application/json';
  }

  const options = {
    method,
    headers: reqHeaders
  };
  if (body) {
    options.body = JSON.stringify(body);
  }

  let statusText = '';
  let statusCode = 0;
  let responseData = null;
  let rawText = '';

  try {
    const res = await fetch(url, options);
    statusCode = res.status;
    statusText = res.statusText;
    rawText = await res.text();
    try {
      responseData = JSON.parse(rawText);
    } catch {
      responseData = rawText;
    }
  } catch (err) {
    statusCode = 500;
    statusText = 'CONNECTION_ERROR';
    responseData = { error: err.message };
  }

  const section = [];
  section.push(`### ${name}`);
  if (notes) {
    section.push(`> [!NOTE]\n> ${notes}\n`);
  }
  section.push('**Request**:');
  section.push('```http');
  section.push(`${method} ${endpoint} HTTP/1.1`);
  section.push(`Host: localhost:8080`);
  for (const [k, v] of Object.entries(reqHeaders)) {
    section.push(`${k}: ${v}`);
  }
  if (body) {
    section.push('');
    section.push(JSON.stringify(body, null, 2));
  }
  section.push('```\n');

  section.push(`**Response**: \`HTTP/1.1 ${statusCode} ${statusText}\``);
  section.push('```json');
  if (responseData && (typeof responseData === 'object' || rawText.trim())) {
    section.push(typeof responseData === 'object' ? JSON.stringify(responseData, null, 2) : rawText);
  } else {
    section.push('/* 204 No Content / Empty Response Body */');
  }
  section.push('```\n');
  section.push('---\n');

  reportSections.push(section.join('\n'));
  console.log(`[PASS] ${method} ${endpoint} -> ${statusCode} ${statusText}`);
  return responseData;
}

async function runAllTests() {
  appendHeader();

  // ==========================================
  // 1. DASHBOARD APIS
  // ==========================================
  reportSections.push('## 1. Dashboard Metrics API\n');
  await testEndpoint({
    name: '1.1 Get Dashboard Summary',
    method: 'GET',
    endpoint: '/dashboard/summary',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Hero aggregation endpoint returning real-time status counts, duplicate counts, and monthly spend.'
  });

  // ==========================================
  // 2. USER APIS
  // ==========================================
  reportSections.push('## 2. User Profile & Team Hierarchy APIs\n');
  await testEndpoint({
    name: '2.1 Get Current User Profile (Staff)',
    method: 'GET',
    endpoint: '/users/me',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Retrieves the active staff user profile (Ram Kumar) with monthly budget limit.'
  });

  await testEndpoint({
    name: '2.2 Get Current User Profile (Manager)',
    method: 'GET',
    endpoint: '/users/me',
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    notes: 'Retrieves manager profile (Rahul Sharma).'
  });

  await testEndpoint({
    name: '2.3 Get Manager Team Members',
    method: 'GET',
    endpoint: '/users/team',
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    notes: 'Manager only: retrieves all direct reports for Rahul Sharma.'
  });

  await testEndpoint({
    name: '2.4 Get All Active Users',
    method: 'GET',
    endpoint: '/users/all',
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    notes: 'Used by persona switcher to list all available accounts.'
  });

  // ==========================================
  // 3. SMART RECEIPT PARSER
  // ==========================================
  reportSections.push('## 3. Smart Receipt Ingestion API\n');
  await testEndpoint({
    name: '3.1 Parse Messy Receipt Text (Uber Taxi)',
    method: 'POST',
    endpoint: '/receipts/parse',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { receiptText: 'UBER Airport Ride 450 INR 14 Aug 2026' },
    notes: 'Tokenizes raw receipt text into structured merchant, amount, category, and date with confidence score.'
  });

  await testEndpoint({
    name: '3.2 Parse Messy Receipt Text (Swiggy Dinner)',
    method: 'POST',
    endpoint: '/receipts/parse',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { receiptText: 'Swiggy Order #9918 Dinner with client Rs. 1450 on 2026-08-25' },
    notes: 'Handles alternative currency prefixes (Rs.) and hyphenated date formats.'
  });

  // ==========================================
  // 4. CLAIM LIFECYCLE & ITEMS
  // ==========================================
  reportSections.push('## 4. Claim Lifecycle & Line Item APIs\n');

  // Create Draft Claim
  const createdClaim = await testEndpoint({
    name: '4.1 Create Draft Claim',
    method: 'POST',
    endpoint: '/claims',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { title: 'Bangalore Tech Summit Trip' },
    notes: 'Auto-generates claim number formatted as CLM-YYYY-XXXXX.'
  });
  const claimId = createdClaim ? createdClaim.claimId : 1;

  // Add Item 1
  const item1 = await testEndpoint({
    name: '4.2 Add Line Item 1 (Taxi)',
    method: 'POST',
    endpoint: `/claims/${claimId}/items`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: {
      merchantName: 'Uber',
      amount: 450.00,
      expenseDate: '2026-08-14',
      category: 'TAXI',
      receiptText: 'UBER Airport Ride 450 INR 14 Aug 2026'
    },
    notes: 'Adds line item, recalculates claim total, and evaluates duplicate detection.'
  });

  // Add Item 2
  const item2 = await testEndpoint({
    name: '4.3 Add Line Item 2 (Meals)',
    method: 'POST',
    endpoint: `/claims/${claimId}/items`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: {
      merchantName: 'Starbucks',
      amount: 350.00,
      expenseDate: '2026-08-14',
      category: 'MEALS',
      receiptText: 'Starbucks Coffee 350 INR'
    },
    notes: 'Updates claim totalAmount automatically.'
  });
  const itemId2 = item2 ? item2.id : 2;

  // Update Item 2
  await testEndpoint({
    name: '4.4 Update Line Item 2',
    method: 'PUT',
    endpoint: `/claims/${claimId}/items/${itemId2}`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: {
      merchantName: 'Starbucks Cafe',
      amount: 380.00,
      expenseDate: '2026-08-14',
      category: 'MEALS',
      receiptText: 'Starbucks Coffee & Muffin 380 INR'
    },
    notes: 'Updates line item and adjusts total amount.'
  });

  // Delete Item 2
  await testEndpoint({
    name: '4.5 Delete Line Item 2',
    method: 'DELETE',
    endpoint: `/claims/${claimId}/items/${itemId2}`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Removes line item from draft claim.'
  });

  // Get Claim Details
  await testEndpoint({
    name: '4.6 Get Full Claim Details',
    method: 'GET',
    endpoint: `/claims/${claimId}`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Returns claim details, line items, approval audit trail, and payment status.'
  });

  // Update Claim Title
  await testEndpoint({
    name: '4.7 Update Claim Title',
    method: 'PUT',
    endpoint: `/claims/${claimId}`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { title: 'Bangalore Tech Summit & Client Meetings' },
    notes: 'Draft title update.'
  });

  // List My Claims
  await testEndpoint({
    name: '4.8 List My Claims',
    method: 'GET',
    endpoint: '/claims/my',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Retrieves all claims submitted by the currently authenticated user.'
  });

  // List My Claims Filtered by Status
  await testEndpoint({
    name: '4.9 List My Claims Filtered by Status',
    method: 'GET',
    endpoint: '/claims/my?status=DRAFT',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Filter claims by DRAFT status.'
  });

  // Submit Claim
  await testEndpoint({
    name: '4.10 Submit Claim for Manager Sign-Off',
    method: 'POST',
    endpoint: `/claims/${claimId}/submit`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Validates transition from DRAFT -> SUBMITTED and sets submittedAt timestamp.'
  });

  // ==========================================
  // 5. MANAGER APPROVAL & GUARDRAILS
  // ==========================================
  reportSections.push('## 5. Manager Approvals & Guardrails\n');

  await testEndpoint({
    name: '5.1 Get Manager Pending Approvals Inbox',
    method: 'GET',
    endpoint: '/claims/pending-approvals',
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    notes: 'Manager Rahul Sharma views claims submitted by his direct report team.'
  });

  await testEndpoint({
    name: '5.2 Get Team Claims Overview',
    method: 'GET',
    endpoint: '/claims/team',
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    notes: 'Retrieves all team claims across all statuses.'
  });

  // Manager Approve
  await testEndpoint({
    name: '5.3 Manager Approves Submitted Claim',
    method: 'POST',
    endpoint: `/claims/${claimId}/approve`,
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    body: { comments: 'Verified travel tickets. Approved.' },
    notes: 'Signs off claim, creates audit log entry, and moves status to APPROVED.'
  });

  // Manager Self-Approval Block (Guardrail)
  await testEndpoint({
    name: '5.4 Manager Self-Approval Guardrail (Strictly Prohibited)',
    method: 'POST',
    endpoint: '/claims/6/approve',
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    body: { comments: 'Self approving my claim' },
    notes: 'CRITICAL ASSIGNMENT REQUIREMENT: Manager Rahul attempting to approve his own claim #6 is strictly blocked with HTTP 403 Forbidden.'
  });

  // Manager Reject
  await testEndpoint({
    name: '5.5 Manager Rejects Claim with Reason',
    method: 'POST',
    endpoint: '/claims/4/reject',
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    body: { reason: 'Duplicate receipt detected. Please provide updated tax invoice.' },
    notes: 'Rejects claim #4, creates audit log entry with reason, and enables employee to re-edit.'
  });

  // ==========================================
  // 5.6 VERIFICATION SUITE 1: REJECTED -> EDITED -> RESUBMITTED
  // ==========================================
  reportSections.push('### Verification Suite 1: Full Rejection -> Edit -> Resubmission Lifecycle\n');

  await testEndpoint({
    name: '5.6.1 Staff Edits Rejected Claim',
    method: 'PUT',
    endpoint: '/claims/4',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { title: 'Offsite Team Strategy (Revised with Tax Invoices)' },
    notes: 'Staff (Ram) modifies the rejected claim. Editing is permitted because status is REJECTED.'
  });

  await testEndpoint({
    name: '5.6.2 Staff Resubmits Corrected Claim',
    method: 'POST',
    endpoint: '/claims/4/submit',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Lifecycle completes: SUBMITTED -> REJECTED -> EDIT -> RESUBMIT -> SUBMITTED.'
  });

  // ==========================================
  // 6. FINANCE & PAYMENT APIS
  // ==========================================
  reportSections.push('## 6. Finance Payout & Payment Terminal State\n');

  await testEndpoint({
    name: '6.1 Get Approved Claims for Payout',
    method: 'GET',
    endpoint: '/finance/approved-claims',
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    notes: 'Finance view of all claims ready for reimbursement payout.'
  });

  // Finance Payout
  await testEndpoint({
    name: '6.2 Finance Disburses Reimbursement Payout',
    method: 'POST',
    endpoint: `/claims/${claimId}/pay`,
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    body: {
      paymentReference: 'PAY-2026-99001',
      remarks: 'Bank transfer processed successfully via NEFT.'
    },
    notes: 'Generates payment reference and marks claim as PAID.'
  });

  // ==========================================
  // 6.3 VERIFICATION SUITE 2: COMPREHENSIVE PAID CLAIM IMMUTABILITY
  // ==========================================
  reportSections.push('### Verification Suite 2: Comprehensive Paid Claim Immutability (5 Prohibited Mutations)\n');

  await testEndpoint({
    name: '6.3.1 Prohibited Mutation: Cannot Approve Paid Claim',
    method: 'POST',
    endpoint: `/claims/${claimId}/approve`,
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    body: { comments: 'Attempting to approve a paid claim' },
    notes: 'PAID -> APPROVED blocked. Returns HTTP 400 Bad Request.'
  });

  await testEndpoint({
    name: '6.3.2 Prohibited Mutation: Cannot Reject Paid Claim',
    method: 'POST',
    endpoint: `/claims/${claimId}/reject`,
    headers: { 'X-User-Id': '1', 'X-Role': 'MANAGER' },
    body: { reason: 'Attempting to reject a paid claim' },
    notes: 'PAID -> REJECTED blocked. Returns HTTP 400 Bad Request.'
  });

  await testEndpoint({
    name: '6.3.3 Prohibited Mutation: Cannot Edit Title of Paid Claim',
    method: 'PUT',
    endpoint: `/claims/${claimId}`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { title: 'Tampered Title on Settled Claim' },
    notes: 'Cannot edit settled claim. Returns HTTP 400 Bad Request.'
  });

  await testEndpoint({
    name: '6.3.4 Prohibited Mutation: Cannot Add Line Item to Paid Claim',
    method: 'POST',
    endpoint: `/claims/${claimId}/items`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: {
      merchantName: 'Phantom Expense',
      amount: 500.00,
      expenseDate: '2026-08-14',
      category: 'OTHER',
      receiptText: 'Fraud attempt'
    },
    notes: 'Cannot add expense items to settled claim. Returns HTTP 400 Bad Request.'
  });

  await testEndpoint({
    name: '6.3.5 Prohibited Mutation: Cannot Delete Paid Claim',
    method: 'DELETE',
    endpoint: `/claims/${claimId}`,
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    notes: 'Cannot delete settled claim. Returns HTTP 400 Bad Request.'
  });

  await testEndpoint({
    name: '6.3.6 Prohibited Mutation: Cannot Pay Paid Claim Again (Double Payout)',
    method: 'POST',
    endpoint: `/claims/${claimId}/pay`,
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    body: {
      paymentReference: 'PAY-DUPLICATE-99',
      remarks: 'Attempting duplicate payout'
    },
    notes: 'PAID -> PAID blocked. Returns HTTP 400 Bad Request.'
  });

  // ==========================================
  // 6.4 VERIFICATION SUITE 3: AUTHORITATIVE SERVER-SIDE ROLE ENFORCEMENT
  // ==========================================
  reportSections.push('### Verification Suite 3: Server-Side Identity Authority (X-Role Spoofing Blocked)\n');

  await testEndpoint({
    name: '6.4.1 Security Check: Ram Claims X-Role: FINANCE on Payout Disbursal',
    method: 'POST',
    endpoint: `/claims/2/pay`,
    headers: { 'X-User-Id': '4', 'X-Role': 'FINANCE' },
    body: {
      paymentReference: 'PAY-SPOOFED',
      remarks: 'Ram trying to disburse money'
    },
    notes: 'CRITICAL SECURITY CHECK: Ram (User #4, EMPLOYEE in DB) passes X-Role: FINANCE. The server authoritatively resolves role from DB entity, ignoring client spoofing. Returns HTTP 403 Forbidden.'
  });

  await testEndpoint({
    name: '6.4.2 Security Check: Ram Claims X-Role: FINANCE on Financial Reports',
    method: 'GET',
    endpoint: '/reports/monthly-spend',
    headers: { 'X-User-Id': '4', 'X-Role': 'FINANCE' },
    notes: 'Ram passes X-Role: FINANCE trying to access company spend data. Blocked with HTTP 403 Forbidden.'
  });

  await testEndpoint({
    name: '6.4.3 Security Check: Ram Claims X-Role: MANAGER on Claim Approval',
    method: 'POST',
    endpoint: '/claims/2/approve',
    headers: { 'X-User-Id': '4', 'X-Role': 'MANAGER' },
    body: { comments: 'Ram approving colleague claim' },
    notes: 'Ram passes X-Role: MANAGER. Blocked with HTTP 403 Forbidden.'
  });

  // ==========================================
  // 7. DUPLICATE DETECTION APIS & DETERMINISTIC BREAKDOWN
  // ==========================================
  reportSections.push('## 7. Duplicate Receipt Detection & Review\n');

  // Create temporary draft claim to trigger deterministic 40-35-20 duplicate score
  const dupClaim = await testEndpoint({
    name: '7.1 Create Draft Claim for Deterministic Duplicate Test',
    method: 'POST',
    endpoint: '/claims',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { title: 'Deterministic Duplicate Scoring Test Claim' },
    notes: 'Claim created to test deterministic 40-35-20 duplicate scoring algorithm.'
  });

  if (dupClaim && dupClaim.claimId) {
    reportSections.push('### Verification Suite 4: Deterministic Duplicate Detection Formula (40-35-20 = 95%)\n');
    await testEndpoint({
      name: '7.2 Deterministic Duplicate Scoring (Amount 40 + Merchant 35 + Date 20 = 95%)',
      method: 'POST',
      endpoint: `/claims/${dupClaim.claimId}/items`,
      headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
      body: {
        merchantName: 'Uber Taxi',
        amount: 450.00,
        expenseDate: '2026-08-14',
        category: 'TAXI',
        receiptText: 'Uber Taxi 450 INR'
      },
      notes: 'Matches existing Item #1 (Uber, 450.00, 2026-08-14). Exact Amount = 40.00, Substring Merchant (Uber in Uber Taxi) = 35.00, Exact Date = 20.00. Total = 95.00% >= 80% threshold -> PENDING_REVIEW alert generated.'
    });
  }

  await testEndpoint({
    name: '7.3 Get Duplicate Receipt Alerts with Component Scores',
    method: 'GET',
    endpoint: '/duplicates',
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    notes: 'Finance view of all duplicate alerts showing exact amountScore, merchantScore, dateScore, similarityScore, and PENDING_REVIEW status.'
  });

  await testEndpoint({
    name: '7.4 Finance Reviews Duplicate Alert',
    method: 'POST',
    endpoint: '/duplicates/1/review',
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    body: { decision: 'CONFIRMED_DUPLICATE' },
    notes: 'Finance marks duplicate as CONFIRMED_DUPLICATE or FALSE_POSITIVE.'
  });

  // ==========================================
  // 8. FINANCIAL REPORTING APIS
  // ==========================================
  reportSections.push('## 8. Monthly Financial Reports & Compliance\n');

  await testEndpoint({
    name: '8.1 Monthly Spend Summary Report',
    method: 'GET',
    endpoint: '/reports/monthly-spend',
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    notes: 'Calculates total spend across all approved and paid claims for the current month.'
  });

  await testEndpoint({
    name: '8.2 Spend by Employee Report',
    method: 'GET',
    endpoint: '/reports/employee-spend',
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    notes: 'Answers: Who spent what? Aggregates total expenditure per employee.'
  });

  await testEndpoint({
    name: '8.3 Spend by Expense Category Report',
    method: 'GET',
    endpoint: '/reports/category-spend',
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    notes: 'Answers: Under which category? Categorical breakdown (Travel, Meals, Supplies, Taxi, Other).'
  });

  await testEndpoint({
    name: '8.4 Over-Limit Employees Report',
    method: 'GET',
    endpoint: '/reports/over-limit',
    headers: { 'X-User-Id': '3', 'X-Role': 'FINANCE' },
    notes: 'Answers: Who has gone over their limit? Flags employees exceeding their monthly limit with excess amount.'
  });

  // ==========================================
  // 9. DRAFT CLAIM DELETION
  // ==========================================
  reportSections.push('## 9. Draft Claim Deletion\n');

  const tempClaim = await testEndpoint({
    name: '9.1 Create Temporary Draft Claim',
    method: 'POST',
    endpoint: '/claims',
    headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
    body: { title: 'Temporary Draft to Delete' },
    notes: 'Temporary claim created for deletion test.'
  });

  if (tempClaim && tempClaim.claimId) {
    await testEndpoint({
      name: '9.2 Delete Draft Claim',
      method: 'DELETE',
      endpoint: `/claims/${tempClaim.claimId}`,
      headers: { 'X-User-Id': '4', 'X-Role': 'STAFF' },
      notes: 'Draft claims can be deleted by owner. Returns HTTP 204 No Content.'
    });
  }

  // Save report
  fs.writeFileSync(OUTPUT_FILE, reportSections.join('\n'), 'utf8');
  console.log(`\nAll API tests completed successfully!`);
  console.log(`Report written to: ${OUTPUT_FILE}`);
}

runAllTests().catch(console.error);
