# Comprehensive API Test Suite & Response Generator
$baseUrl = "http://localhost:8080/api/v1"
$outputFile = "d:\VSP\API_TEST_RESULTS.md"

$report = @()
$report += "# Comprehensive API Execution & Verification Report"
$report += ""
$report += "This document contains real HTTP requests and live responses generated by testing every endpoint against the running application."
$report += ""
$report += "**Execution Timestamp**: " + (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
$report += "**Base URL**: `$baseUrl`"
$report += "**Target Environment**: Local Spring Boot Server (`http://localhost:8080`)"
$report += ""
$report += "---"
$report += ""

function Test-Endpoint {
    param (
        [string]$Category,
        [string]$Name,
        [string]$Method,
        [string]$Path,
        [hashtable]$Headers,
        [string]$Body = $null,
        [string]$Notes = ""
    )

    $url = "$baseUrl$Path"
    $reqHeaders = @{}
    if ($Headers) {
        foreach ($k in $Headers.Keys) {
            $reqHeaders[$k] = $Headers[$k]
        }
    }
    if ($Body) {
        $reqHeaders["Content-Type"] = "application/json"
    }

    $statusStr = ""
    $respBodyStr = ""

    try {
        if ($Method -eq "GET") {
            $response = Invoke-WebRequest -Uri $url -Method Get -Headers $reqHeaders -UseBasicParsing -TimeoutSec 10
            $statusStr = "$([int]$response.StatusCode) $($response.StatusDescription)"
            $respBodyStr = $response.Content
        } elseif ($Method -eq "POST") {
            $response = Invoke-WebRequest -Uri $url -Method Post -Headers $reqHeaders -Body $Body -UseBasicParsing -TimeoutSec 10
            $statusStr = "$([int]$response.StatusCode) $($response.StatusDescription)"
            $respBodyStr = $response.Content
        } elseif ($Method -eq "PUT") {
            $response = Invoke-WebRequest -Uri $url -Method Put -Headers $reqHeaders -Body $Body -UseBasicParsing -TimeoutSec 10
            $statusStr = "$([int]$response.StatusCode) $($response.StatusDescription)"
            $respBodyStr = $response.Content
        } elseif ($Method -eq "DELETE") {
            $response = Invoke-WebRequest -Uri $url -Method Delete -Headers $reqHeaders -UseBasicParsing -TimeoutSec 10
            $statusStr = "$([int]$response.StatusCode) $($response.StatusDescription)"
            $respBodyStr = $response.Content
        }
    } catch {
        if ($_.Exception.Response) {
            $resp = $_.Exception.Response
            $statusStr = "$([int]$resp.StatusCode) $($resp.StatusDescription)"
            $stream = $resp.GetResponseStream()
            $reader = New-Object System.IO.StreamReader($stream)
            $respBodyStr = $reader.ReadToEnd()
        } else {
            $statusStr = "ERROR"
            $respBodyStr = $_.Exception.Message
        }
    }

    # Format JSON response if valid
    $formattedResp = $respBodyStr
    try {
        if ($respBodyStr -and $respBodyStr.Trim().StartsWith("{") -or $respBodyStr.Trim().StartsWith("[")) {
            $jsonObj = $respBodyStr | ConvertFrom-Json
            $formattedResp = $jsonObj | ConvertTo-Json -Depth 10
        }
    } catch {}

    # Format JSON request if present
    $formattedReq = $Body
    try {
        if ($Body -and ($Body.Trim().StartsWith("{") -or $Body.Trim().StartsWith("["))) {
            $jsonObj = $Body | ConvertFrom-Json
            $formattedReq = $jsonObj | ConvertTo-Json -Depth 10
        }
    } catch {}

    $script:report += "### $Name"
    if ($Notes) {
        $script:report += "> [!NOTE]"
        $script:report += "> $Notes"
        $script:report += ""
    }
    $script:report += "**Request**:"
    $script:report += "```http"
    $script:report += "$Method $Path HTTP/1.1"
    $script:report += "Host: localhost:8080"
    foreach ($k in $reqHeaders.Keys) {
        $script:report += "$k: $($reqHeaders[$k])"
    }
    if ($formattedReq) {
        $script:report += ""
        $script:report += $formattedReq
    }
    $script:report += "```"
    $script:report += ""
    $script:report += "**Response**: `HTTP/1.1 $statusStr`"
    $script:report += "```json"
    if ($formattedResp -and $formattedResp.Trim()) {
        $script:report += $formattedResp
    } else {
        $script:report += "/* 204 No Content / Empty Body */"
    }
    $script:report += "```"
    $script:report += ""
    $script:report += "---"
    $script:report += ""

    Write-Host "Tested: $Method $Path -> $statusStr" -ForegroundColor Green
    return $respBodyStr
}

# ==========================================
# 1. DASHBOARD APIS
# ==========================================
$report += "## 1. Dashboard Metrics API"
$report += ""
Test-Endpoint -Category "Dashboard" -Name "1.1 Get Dashboard Summary" -Method "GET" -Path "/dashboard/summary" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Hero aggregation endpoint returning real-time status counts, duplicate counts, and monthly spend."

# ==========================================
# 2. USER APIS
# ==========================================
$report += "## 2. User Profile & Hierarchy APIs"
$report += ""
Test-Endpoint -Category "Users" -Name "2.1 Get Current User Profile (Staff)" -Method "GET" -Path "/users/me" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Retrieves the active user profile (Ram Kumar) with monthly budget limit."
Test-Endpoint -Category "Users" -Name "2.2 Get Current User Profile (Manager)" -Method "GET" -Path "/users/me" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Notes "Retrieves manager profile (Rahul Sharma)."
Test-Endpoint -Category "Users" -Name "2.3 Get Manager Team Members" -Method "GET" -Path "/users/team" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Notes "Manager only: retrieves all direct reports for Rahul Sharma."
Test-Endpoint -Category "Users" -Name "2.4 Get All Active Users" -Method "GET" -Path "/users/all" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Notes "Used by persona switcher to list all available accounts."

# ==========================================
# 3. SMART RECEIPT PARSING
# ==========================================
$report += "## 3. Smart Receipt Ingestion API"
$report += ""
Test-Endpoint -Category "Receipts" -Name "3.1 Parse Messy Receipt Text (Uber Taxi)" -Method "POST" -Path "/receipts/parse" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"receiptText":"UBER Airport Ride 450 INR 14 Aug 2026"}' -Notes "Tokenizes raw receipt text into structured merchant, amount, category, and date with confidence score."
Test-Endpoint -Category "Receipts" -Name "3.2 Parse Messy Receipt Text (Swiggy Dinner)" -Method "POST" -Path "/receipts/parse" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"receiptText":"Swiggy Order #9918 Dinner with client Rs. 1450 on 2026-08-25"}' -Notes "Handles alternative currency prefixes and date formats."

# ==========================================
# 4. CLAIM LIFECYCLE APIS
# ==========================================
$report += "## 4. Claim Lifecycle & Line Item APIs"
$report += ""

# Create new claim
$createdClaimJson = Test-Endpoint -Category "Claims" -Name "4.1 Create Draft Claim" -Method "POST" -Path "/claims" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"title":"Bangalore Tech Summit Trip"}' -Notes "Auto-generates claim number formatted as CLM-YYYY-XXXXX."
$createdClaim = $createdClaimJson | ConvertFrom-Json
$claimId = $createdClaim.claimId

# Add Line Item 1
$item1Json = Test-Endpoint -Category "Claims" -Name "4.2 Add Expense Item to Draft Claim" -Method "POST" -Path "/claims/$claimId/items" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"merchantName":"Uber","amount":450.00,"expenseDate":"2026-08-14","category":"TAXI","receiptText":"UBER Airport Ride 450 INR 14 Aug 2026"}' -Notes "Adds expense item and evaluates duplicate detection engine in real-time."
$item1 = $item1Json | ConvertFrom-Json
$itemId1 = $item1.id

# Add Line Item 2
$item2Json = Test-Endpoint -Category "Claims" -Name "4.3 Add Second Expense Item" -Method "POST" -Path "/claims/$claimId/items" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"merchantName":"Starbucks","amount":350.00,"expenseDate":"2026-08-14","category":"MEALS","receiptText":"Starbucks Coffee 350 INR"}' -Notes "Updates claim totalAmount automatically."
$item2 = $item2Json | ConvertFrom-Json
$itemId2 = $item2.id

# Update Line Item 2
Test-Endpoint -Category "Claims" -Name "4.4 Update Expense Item" -Method "PUT" -Path "/claims/$claimId/items/$itemId2" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"merchantName":"Starbucks Cafe","amount":380.00,"expenseDate":"2026-08-14","category":"MEALS","receiptText":"Starbucks Coffee & Muffin 380 INR"}' -Notes "Updates line item and recalculates claim total."

# Delete Line Item 2
Test-Endpoint -Category "Claims" -Name "4.5 Delete Expense Item" -Method "DELETE" -Path "/claims/$claimId/items/$itemId2" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Removes line item and adjusts claim total."

# Get Claim Details
Test-Endpoint -Category "Claims" -Name "4.6 Get Full Claim Details" -Method "GET" -Path "/claims/$claimId" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Returns claim metadata, line items, approval audit trail, and payment status."

# Update Claim Title
Test-Endpoint -Category "Claims" -Name "4.7 Update Claim Title" -Method "PUT" -Path "/claims/$claimId" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"title":"Bangalore Tech Summit & Client Meetings"}' -Notes "Title can only be edited while claim is in DRAFT or REJECTED state."

# List My Claims
Test-Endpoint -Category "Claims" -Name "4.8 List My Claims" -Method "GET" -Path "/claims/my" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Retrieves all claims submitted by the currently authenticated user."
Test-Endpoint -Category "Claims" -Name "4.9 List My Claims Filtered by Status" -Method "GET" -Path "/claims/my?status=DRAFT" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Filter claims by DRAFT status."

# Submit Claim
Test-Endpoint -Category "Claims" -Name "4.10 Submit Claim for Manager Sign-Off" -Method "POST" -Path "/claims/$claimId/submit" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Validates transition from DRAFT -> SUBMITTED and sets submittedAt timestamp."

# ==========================================
# 5. MANAGER APPROVAL & GUARDRAILS
# ==========================================
$report += "## 5. Manager Approvals & Guardrails"
$report += ""

Test-Endpoint -Category "Approvals" -Name "5.1 Get Manager Pending Approvals Inbox" -Method "GET" -Path "/claims/pending-approvals" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Notes "Manager Rahul Sharma views claims submitted by his direct report team."
Test-Endpoint -Category "Approvals" -Name "5.2 Get Team Claims Overview" -Method "GET" -Path "/claims/team" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Notes "Retrieves all team claims across all statuses."

# Manager Approve
Test-Endpoint -Category "Approvals" -Name "5.3 Manager Approves Submitted Claim" -Method "POST" -Path "/claims/$claimId/approve" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Body '{"comments":"Verified travel itinerary. Approved."}' -Notes "Signs off claim, creates audit log entry, and moves status to APPROVED."

# Manager Self-Approval Block (Guardrail)
Test-Endpoint -Category "Approvals" -Name "5.4 Manager Self-Approval Guardrail (Strictly Prohibited)" -Method "POST" -Path "/claims/6/approve" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Body '{"comments":"Self approving my claim"}' -Notes "CRITICAL ASSIGNMENT REQUIREMENT: Manager Rahul attempting to approve his own claim #6 must be BLOCKED with HTTP 403 Forbidden."

# Manager Reject Another Claim
Test-Endpoint -Category "Approvals" -Name "5.5 Manager Rejects Claim with Reason" -Method "POST" -Path "/claims/4/reject" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Body '{"reason":"Duplicate receipt detected. Please provide updated tax invoice."}' -Notes "Rejects claim #4, creates audit log entry with reason, and enables employee to re-edit."

# ==========================================
# 6. FINANCE & PAYMENT APIS
# ==========================================
$report += "## 6. Finance Payout & Payment Terminal State"
$report += ""

Test-Endpoint -Category "Finance" -Name "6.1 Get Approved Claims for Payout" -Method "GET" -Path "/finance/approved-claims" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Notes "Finance view of all claims ready for reimbursement payout."

# Finance Payout
Test-Endpoint -Category "Finance" -Name "6.2 Finance Disburses Reimbursement Payout" -Method "POST" -Path "/claims/$claimId/pay" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Body '{"paymentReference":"PAY-2026-99001","remarks":"Bank transfer processed successfully via NEFT."}' -Notes "Generates payment reference and marks claim as PAID."

# Terminal State Check (Guardrail)
Test-Endpoint -Category "Finance" -Name "6.3 Terminal State Guardrail: Paid Claims Cannot Revert" -Method "POST" -Path "/claims/$claimId/approve" -Headers @{"X-User-Id"="1"; "X-Role"="MANAGER"} -Body '{"comments":"Attempting to approve a paid claim"}' -Notes "CRITICAL ASSIGNMENT REQUIREMENT: A paid claim is finished and cannot go backwards. Returns HTTP 400 Bad Request."

# ==========================================
# 7. DUPLICATE DETECTION APIS
# ==========================================
$report += "## 7. Duplicate Receipt Detection & Review"
$report += ""

Test-Endpoint -Category "Duplicates" -Name "7.1 Get Duplicate Receipt Alerts" -Method "GET" -Path "/duplicates" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Notes "Finance view of all duplicate alerts including component scores (Amount, Merchant, Date, Similarity)."
Test-Endpoint -Category "Duplicates" -Name "7.2 Finance Reviews Duplicate Alert" -Method "POST" -Path "/duplicates/1/review" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Body '{"decision":"CONFIRMED_DUPLICATE"}' -Notes "Finance marks duplicate as CONFIRMED_DUPLICATE or FALSE_POSITIVE."

# ==========================================
# 8. FINANCIAL REPORTING APIS
# ==========================================
$report += "## 8. Monthly Financial Reports & Compliance"
$report += ""

Test-Endpoint -Category "Reports" -Name "8.1 Monthly Spend Summary Report" -Method "GET" -Path "/reports/monthly-spend" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Notes "Calculates total spend across all approved and paid claims for the current month."
Test-Endpoint -Category "Reports" -Name "8.2 Spend by Employee Report" -Method "GET" -Path "/reports/employee-spend" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Notes "Answers: Who spent what? Aggregates total expenditure per employee."
Test-Endpoint -Category "Reports" -Name "8.3 Spend by Expense Category Report" -Method "GET" -Path "/reports/category-spend" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Notes "Answers: Under which category? Categorical breakdown (Travel, Meals, Supplies, Taxi, Other)."
Test-Endpoint -Category "Reports" -Name "8.4 Over-Limit Employees Report" -Method "GET" -Path "/reports/over-limit" -Headers @{"X-User-Id"="3"; "X-Role"="FINANCE"} -Notes "Answers: Who has gone over their limit? Flags employees exceeding their monthly limit with excess amount."

# ==========================================
# 9. DRAFT DELETION API
# ==========================================
$report += "## 9. Draft Claim Deletion"
$report += ""
$tempClaimJson = Test-Endpoint -Category "Claims" -Name "9.1 Create Temporary Draft Claim" -Method "POST" -Path "/claims" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Body '{"title":"Temporary Draft to be Deleted"}'
$tempClaim = $tempClaimJson | ConvertFrom-Json
Test-Endpoint -Category "Claims" -Name "9.2 Delete Draft Claim" -Method "DELETE" -Path "/claims/$($tempClaim.claimId)" -Headers @{"X-User-Id"="4"; "X-Role"="STAFF"} -Notes "Draft claims can be deleted by owner. Returns HTTP 204 No Content."

# Write Report File
$report | Out-File -FilePath $outputFile -Encoding UTF8
Write-Host "All tests completed. Report generated at $outputFile" -ForegroundColor Cyan
